/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProjectsService } from "../projects.service";
import { ProjectsCreateInput } from "./ProjectsCreateInput";
import { Projects } from "./Projects";
import { ProjectsFindManyArgs } from "./ProjectsFindManyArgs";
import { ProjectsWhereUniqueInput } from "./ProjectsWhereUniqueInput";
import { ProjectsUpdateInput } from "./ProjectsUpdateInput";
import { CaseStudiesFindManyArgs } from "../../caseStudies/base/CaseStudiesFindManyArgs";
import { CaseStudies } from "../../caseStudies/base/CaseStudies";
import { CaseStudiesWhereUniqueInput } from "../../caseStudies/base/CaseStudiesWhereUniqueInput";

export class ProjectsControllerBase {
  constructor(protected readonly service: ProjectsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Projects })
  async createProjects(
    @common.Body() data: ProjectsCreateInput
  ): Promise<Projects> {
    return await this.service.createProjects({
      data: data,
      select: {
        clientType: true,
        createdAt: true,
        description: true,
        id: true,
        keyFeatures: true,
        results: true,
        screenshots: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Projects] })
  @ApiNestedQuery(ProjectsFindManyArgs)
  async projectsItems(@common.Req() request: Request): Promise<Projects[]> {
    const args = plainToClass(ProjectsFindManyArgs, request.query);
    return this.service.projectsItems({
      ...args,
      select: {
        clientType: true,
        createdAt: true,
        description: true,
        id: true,
        keyFeatures: true,
        results: true,
        screenshots: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async projects(
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<Projects | null> {
    const result = await this.service.projects({
      where: params,
      select: {
        clientType: true,
        createdAt: true,
        description: true,
        id: true,
        keyFeatures: true,
        results: true,
        screenshots: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProjects(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() data: ProjectsUpdateInput
  ): Promise<Projects | null> {
    try {
      return await this.service.updateProjects({
        where: params,
        data: data,
        select: {
          clientType: true,
          createdAt: true,
          description: true,
          id: true,
          keyFeatures: true,
          results: true,
          screenshots: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Projects })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProjects(
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<Projects | null> {
    try {
      return await this.service.deleteProjects({
        where: params,
        select: {
          clientType: true,
          createdAt: true,
          description: true,
          id: true,
          keyFeatures: true,
          results: true,
          screenshots: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/caseStudiesItems")
  @ApiNestedQuery(CaseStudiesFindManyArgs)
  async findCaseStudiesItems(
    @common.Req() request: Request,
    @common.Param() params: ProjectsWhereUniqueInput
  ): Promise<CaseStudies[]> {
    const query = plainToClass(CaseStudiesFindManyArgs, request.query);
    const results = await this.service.findCaseStudiesItems(params.id, {
      ...query,
      select: {
        challenges: true,
        createdAt: true,
        id: true,
        outcomes: true,

        project: {
          select: {
            id: true,
          },
        },

        solutions: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/caseStudiesItems")
  async connectCaseStudiesItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: CaseStudiesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      caseStudiesItems: {
        connect: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/caseStudiesItems")
  async updateCaseStudiesItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: CaseStudiesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      caseStudiesItems: {
        set: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/caseStudiesItems")
  async disconnectCaseStudiesItems(
    @common.Param() params: ProjectsWhereUniqueInput,
    @common.Body() body: CaseStudiesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      caseStudiesItems: {
        disconnect: body,
      },
    };
    await this.service.updateProjects({
      where: params,
      data,
      select: { id: true },
    });
  }
}
